complexity:
    LongParameterList:
        ignoreDefaultParameters: true

style:
    MagicNumber:
        ignorePropertyDeclaration: true
        ignoreCompanionObjectPropertyDeclaration: true
    UnusedPrivateMember:
        ignoreAnnotated: [ 'Preview' ]

naming:
    TopLevelPropertyNaming:
        constantPattern: '[A-Z][A-Za-z0-9]*'
    FunctionNaming:
        ignoreAnnotated: [ 'Composable' ]
